@startuml
skinparam classAttributeIconSize 0

class Context {
   　- state
   　+ Request()
   {method} 　　　　　　　　　 
   {method} 　　　　　　　　　
}
note "Request() {\n    state.Handle();\n}" as N1

interface State {
  　 + Handle()
   {method} 　　　　　　　　　 
   {method} 　　　　　　　　　
}

object ConcreateStateA {
  　  + Handle()
   {method} 　　　　　　　　　 
   {method} 　　　　　　　　　
}
object ConcreateStateB {
  　  + Handle()
   {method} 　　　　　　　　　 
   {method} 　　　　　　　　　
}

Context o-> State
Context .. N1
State <|.. ConcreateStateA
State <|.. ConcreateStateB

@enduml